kind: pipeline
type: ssh
name: default

server:
  host: seint-drone.digitalstacks.net
  user: SaintNandarOo
  password:
    from_secret: password


steps:
- name: greeting
  commands:
  - echo hello world
