pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: seint-drone.digitalstacks.net
    username: SaintNandarOo
+   volumes:
+     - /root/drone_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa
    script:
      - echo "test ssh"
